print("="*19, "DESAFIO 27", "="*19)
print("Apenas o primeiro e ultimo nome...")
nome = str(input("Digite seu nome completo: ")).strip()
nomeFormal = nome.split()
print("É um prazer te conhecer.")
print("Seu primeiro nome é {}.".format(nomeFormal[0]))
print("E seu ultimo nome é {}.".format(nomeFormal[len(nomeFormal) - 1]))
print("Sendo assim seu nome formal é {} {}".format(nomeFormal[0], nomeFormal[len(nomeFormal) - 1]))
print("="*50)
