print("="*19, "DESAFIO 22", "="*19)
print("Mostrador de nome detalhado...")
nome = str(input("Digite seu nome por favor: ")).strip()
print("Analisando seu nome.....")
print("Olá {}.".format(nome))
print("Seu nome somente com letras minúsculas é {}.".format(nome.lower()))
print("Seu nome somente com letras maiúsculas é {}.".format(nome.upper()))
print("Seu nome tem {} letras.".format(len(nome) - nome.count(" ")))
separado = nome.split()
print("Seu priemiro nome é {} e tem {} letras.".format(separado[0], len(separado[0])))
print("="*50)
